server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location = / {
        return 302 /censo-app/;
    }

    location /censo-app {
        try_files $uri $uri/ /censo-app/index.html;
    }

    location = /censo-app/index.html {
        add_header Cache-Control "no-cache";
    }
}
